export const days = [
  {
    1603926359168: {
      kcal: 242,
      name: "Burrito with chicken",
      portion: 386,
      portions: [
        {
          gramWeight: 142,
          id: 217107,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62076",
          portionDescription: "1 small burrito",
          sequenceNumber: 1,
        },
        {
          gramWeight: 238,
          id: 213554,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61311",
          portionDescription: "1 medium burrito",
          sequenceNumber: 2,
        },
        {
          gramWeight: 386,
          id: 211992,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60985",
          portionDescription: "1 large burrito",
          sequenceNumber: 3,
        },
        {
          gramWeight: 550,
          id: 223240,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64385",
          portionDescription: "1 extra large burrito",
          sequenceNumber: 4,
        },
        {
          gramWeight: 238,
          id: 223351,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64393",
          portionDescription: "1 burrito, NS as to size",
          sequenceNumber: 5,
        },
        {
          gramWeight: 175,
          id: 200083,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 6,
        },
      ],
    },
    1603926381188: {
      kcal: 52,
      name: "Apple, raw",
      portion: 223,
      portions: [
        {
          gramWeight: 35,
          id: 210108,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60608",
          portionDescription: "1 crabapple",
          sequenceNumber: 4,
        },
        {
          gramWeight: 125,
          id: 195849,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10010",
          portionDescription: "1 cup, NFS",
          sequenceNumber: 5,
        },
        {
          gramWeight: 110,
          id: 198032,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10161",
          portionDescription: "1 cup, sliced",
          sequenceNumber: 6,
        },
        {
          gramWeight: 125,
          id: 197940,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10141",
          portionDescription: "1 cup, quartered or chopped",
          sequenceNumber: 7,
        },
        {
          gramWeight: 17,
          id: 216120,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61935",
          portionDescription: "1 slice",
          sequenceNumber: 8,
        },
        {
          gramWeight: 26,
          id: 207149,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "40092",
          portionDescription: "1 oz, with skin, yields",
          sequenceNumber: 9,
        },
        {
          gramWeight: 14,
          id: 215616,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61820",
          portionDescription: "1 ring",
          sequenceNumber: 10,
        },
        {
          gramWeight: 7,
          id: 218184,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62308",
          portionDescription: "1 thin slice",
          sequenceNumber: 12,
        },
        {
          gramWeight: 149,
          id: 221688,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64211",
          portionDescription: '1 small (2-3/4" dia)',
          sequenceNumber: 13,
        },
        {
          gramWeight: 182,
          id: 213419,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61257",
          portionDescription: '1 medium (3" dia)',
          sequenceNumber: 14,
        },
        {
          gramWeight: 223,
          id: 221689,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64212",
          portionDescription: '1 large (3-1/4" dia)',
          sequenceNumber: 15,
        },
      ],
    },
    1603926623313: {
      kcal: 250,
      name: "Meat spread or potted meat sandwich",
      portion: 107,
      portions: [
        {
          gramWeight: 107,
          id: 215792,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61853",
          portionDescription: "1 sandwich",
          sequenceNumber: 1,
        },
      ],
    },
    1603926640954: {
      kcal: 89,
      name: "Banana, raw",
      portion: 118,
      portions: [
        {
          gramWeight: 81,
          id: 219206,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63490",
          portionDescription: '1 extra small (less than 6" long)',
          sequenceNumber: 1,
        },
        {
          gramWeight: 101,
          id: 219057,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63479",
          portionDescription: '1 small (6" to 6-7/8" long)',
          sequenceNumber: 2,
        },
        {
          gramWeight: 118,
          id: 219233,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63522",
          portionDescription: '1 medium (7" to 7-7/8" long)',
          sequenceNumber: 3,
        },
        {
          gramWeight: 136,
          id: 219235,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63524",
          portionDescription: '1 large (8" to 8-7/8" long)',
          sequenceNumber: 4,
        },
        {
          gramWeight: 152,
          id: 219234,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63523",
          portionDescription: '1 extra large (9" or longer)',
          sequenceNumber: 5,
        },
        {
          gramWeight: 6,
          id: 216123,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61935",
          portionDescription: "1 slice",
          sequenceNumber: 6,
        },
        {
          gramWeight: 150,
          id: 195860,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10010",
          portionDescription: "1 cup, NFS",
          sequenceNumber: 7,
        },
        {
          gramWeight: 150,
          id: 198038,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10161",
          portionDescription: "1 cup, sliced",
          sequenceNumber: 8,
        },
        {
          gramWeight: 225,
          id: 197672,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10118",
          portionDescription: "1 cup, mashed",
          sequenceNumber: 9,
        },
        {
          gramWeight: 16,
          id: 219236,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63525",
          portionDescription: "1 linear inch",
          sequenceNumber: 10,
        },
        {
          gramWeight: 18,
          id: 204556,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "40016",
          portionDescription: "1 oz yields",
          sequenceNumber: 11,
        },
      ],
    },
  },
  {
    1604007760273: {
      kcal: 282,
      name:
        "Double cheeseburger, 2 small patties, with condiments, on bun, from fast food / restaurant (McDonald's Double Cheeseburger)",
      portion: 100,
      portions: [
        {
          gramWeight: 165,
          id: 209101,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60193",
          portionDescription: "1 McDonald's Double cheeseburger",
          sequenceNumber: 1,
        },
      ],
    },
  },
  {
    1604264978426: {
      kcal: 264,
      name: "Bagel",
      portion: 100,
      portions: [
        {
          gramWeight: 46,
          id: 258591,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64555",
          portionDescription: "1 Bagel Thin",
          sequenceNumber: 10,
        },
        {
          gramWeight: 105,
          id: 253498,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62862",
          portionDescription: "1 regular",
          sequenceNumber: 8,
        },
        {
          gramWeight: 69,
          id: 252045,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62015",
          portionDescription: "1 small",
          sequenceNumber: 7,
        },
        {
          gramWeight: 26,
          id: 250092,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61467",
          portionDescription: "1 miniature",
          sequenceNumber: 6,
        },
        {
          gramWeight: 131,
          id: 248170,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60919",
          portionDescription: "1 large",
          sequenceNumber: 9,
        },
      ],
    },
    1604265032859: {
      kcal: 600,
      name: "Breakfast ",
    },
    1604343362825: {
      kcal: 52,
      name: "Apple, raw",
      portion: 242,
      portions: [
        {
          gramWeight: 34,
          id: 256154,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64236",
          portionDescription: "1 single serving package",
          sequenceNumber: 7,
        },
        {
          gramWeight: 165,
          id: 252155,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62015",
          portionDescription: "1 small",
          sequenceNumber: 1,
        },
        {
          gramWeight: 25,
          id: 251691,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61935",
          portionDescription: "1 slice",
          sequenceNumber: 5,
        },
        {
          gramWeight: 200,
          id: 249331,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61238",
          portionDescription: "1 medium",
          sequenceNumber: 2,
        },
        {
          gramWeight: 242,
          id: 248284,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60919",
          portionDescription: "1 large",
          sequenceNumber: 3,
        },
        {
          gramWeight: 295,
          id: 247556,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60749",
          portionDescription: "1 extra large",
          sequenceNumber: 4,
        },
        {
          gramWeight: 125,
          id: 239215,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 6,
        },
      ],
    },
  },
  {
    1604264700582: {
      kcal: 283,
      name: "Egg, Benedict",
      portion: 155,
      portions: [
        {
          gramWeight: 155,
          id: 247422,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60710",
          portionDescription: "1 egg",
          sequenceNumber: 1,
        },
      ],
    },
    1604264731313: {
      kcal: 48,
      name: "Orange juice, 100%, NFS",
      portion: 209,
      portions: [
        {
          gramWeight: 124,
          id: 256256,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64294",
          portionDescription: "1 individual school container",
          sequenceNumber: 6,
        },
        {
          gramWeight: 209,
          id: 255478,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64075",
          portionDescription: "1 juice box/pouch (6.75 fl oz)",
          sequenceNumber: 5,
        },
        {
          gramWeight: 131,
          id: 254256,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63848",
          portionDescription: "1 fun size box (4.23 fl oz)",
          sequenceNumber: 4,
        },
        {
          gramWeight: 23,
          id: 242017,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "30009",
          portionDescription: "1 fl oz (with ice)",
          sequenceNumber: 2,
        },
        {
          gramWeight: 31,
          id: 241856,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "30008",
          portionDescription: "1 fl oz (NFS)",
          sequenceNumber: 3,
        },
        {
          gramWeight: 31,
          id: 241686,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "30001",
          portionDescription: "1 fl oz (no ice)",
          sequenceNumber: 1,
        },
      ],
    },
    1604264762464: {
      kcal: 750,
      name: "Lunch ",
    },
    1604264840314: {
      kcal: 168,
      name: "Potato salad, made with mayonnaise",
      portion: 275,
      portions: [
        {
          gramWeight: 275,
          id: 239472,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 1,
        },
      ],
    },
  },
  {
    1604264614072: {
      kcal: 42,
      name: "Peach, raw",
      portion: 150,
      portions: [
        {
          gramWeight: 20,
          id: 260138,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64729",
          portionDescription: "1 slice/chunk",
          sequenceNumber: 2,
        },
        {
          gramWeight: 150,
          id: 247714,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60813",
          portionDescription: "1 fruit",
          sequenceNumber: 1,
        },
        {
          gramWeight: 155,
          id: 239247,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 3,
        },
      ],
    },
    1604264676783: {
      kcal: 174,
      name: "Rice, fried, NFS",
      portion: 198,
      portions: [
        {
          gramWeight: 198,
          id: 238972,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 1,
        },
      ],
    },
    1604287332049: {
      kcal: 52,
      name: "Apple, raw",
      portion: 200,
      portions: [
        {
          gramWeight: 34,
          id: 256154,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64236",
          portionDescription: "1 single serving package",
          sequenceNumber: 7,
        },
        {
          gramWeight: 165,
          id: 252155,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62015",
          portionDescription: "1 small",
          sequenceNumber: 1,
        },
        {
          gramWeight: 25,
          id: 251691,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61935",
          portionDescription: "1 slice",
          sequenceNumber: 5,
        },
        {
          gramWeight: 200,
          id: 249331,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61238",
          portionDescription: "1 medium",
          sequenceNumber: 2,
        },
        {
          gramWeight: 242,
          id: 248284,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60919",
          portionDescription: "1 large",
          sequenceNumber: 3,
        },
        {
          gramWeight: 295,
          id: 247556,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60749",
          portionDescription: "1 extra large",
          sequenceNumber: 4,
        },
        {
          gramWeight: 125,
          id: 239215,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 6,
        },
      ],
    },
  },
  {
    1604331166306: {
      kcal: 233,
      name: "Egg and ham on biscuit",
      portion: 138,
      portions: [
        {
          gramWeight: 138,
          id: 253908,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63512",
          portionDescription: "1 Hardee's biscuit",
          sequenceNumber: 2,
        },
        {
          gramWeight: 138,
          id: 251414,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61853",
          portionDescription: "1 sandwich",
          sequenceNumber: 1,
        },
      ],
    },
    1604331182025: {
      kcal: 32,
      name: "Wonton soup",
      portion: 241,
      portions: [
        {
          gramWeight: 241,
          id: 239172,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 1,
        },
      ],
    },
    1604331205755: {
      kcal: 254,
      name: "Hamburger (Burger King)",
      portion: 100,
      portions: [
        {
          gramWeight: 100,
          id: 247759,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60844",
          portionDescription: "1 hamburger",
          sequenceNumber: 1,
        },
      ],
    },
    1604331236385: {
      kcal: 196,
      name: "Potato, french fries, from fresh, fried",
      portion: 60,
      portions: [
        {
          gramWeight: 5,
          id: 260248,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64739",
          portionDescription: "1 fry, NS as to shape",
          sequenceNumber: 1,
        },
        {
          gramWeight: 8,
          id: 260256,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64740",
          portionDescription: "1 spiral or curly",
          sequenceNumber: 4,
        },
        {
          gramWeight: 70,
          id: 259567,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64636",
          portionDescription: "1 medium, raw, yields",
          sequenceNumber: 9,
        },
        {
          gramWeight: 5,
          id: 259559,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64634",
          portionDescription: "1 crinkle cut",
          sequenceNumber: 7,
        },
        {
          gramWeight: 50,
          id: 259565,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64635",
          portionDescription: "1 small, raw, yields",
          sequenceNumber: 8,
        },
        {
          gramWeight: 2,
          id: 259543,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64632",
          portionDescription: "1 shoestring",
          sequenceNumber: 2,
        },
        {
          gramWeight: 100,
          id: 259569,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64637",
          portionDescription: "1 large, raw, yields",
          sequenceNumber: 10,
        },
        {
          gramWeight: 5,
          id: 259551,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64633",
          portionDescription: "1 straight cut",
          sequenceNumber: 3,
        },
        {
          gramWeight: 8,
          id: 259222,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64605",
          portionDescription: "1 waffle",
          sequenceNumber: 5,
        },
        {
          gramWeight: 9,
          id: 253638,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62927",
          portionDescription: "1 wedge",
          sequenceNumber: 6,
        },
        {
          gramWeight: 15,
          id: 243739,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "40061",
          portionDescription: "1 oz, raw, yields",
          sequenceNumber: 12,
        },
        {
          gramWeight: 60,
          id: 239391,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 11,
        },
      ],
    },
    1604342681719: {
      kcal: 52,
      name: "Apple, raw",
      portion: 242,
      portions: [
        {
          gramWeight: 34,
          id: 256154,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64236",
          portionDescription: "1 single serving package",
          sequenceNumber: 7,
        },
        {
          gramWeight: 165,
          id: 252155,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62015",
          portionDescription: "1 small",
          sequenceNumber: 1,
        },
        {
          gramWeight: 25,
          id: 251691,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61935",
          portionDescription: "1 slice",
          sequenceNumber: 5,
        },
        {
          gramWeight: 200,
          id: 249331,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61238",
          portionDescription: "1 medium",
          sequenceNumber: 2,
        },
        {
          gramWeight: 242,
          id: 248284,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60919",
          portionDescription: "1 large",
          sequenceNumber: 3,
        },
        {
          gramWeight: 295,
          id: 247556,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60749",
          portionDescription: "1 extra large",
          sequenceNumber: 4,
        },
        {
          gramWeight: 125,
          id: 239215,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 6,
        },
      ],
    },
  },
  {
    1604331166306: {
      kcal: 233,
      name: "Egg and ham on biscuit",
      portion: 138,
      portions: [
        {
          gramWeight: 138,
          id: 253908,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "63512",
          portionDescription: "1 Hardee's biscuit",
          sequenceNumber: 2,
        },
        {
          gramWeight: 138,
          id: 251414,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61853",
          portionDescription: "1 sandwich",
          sequenceNumber: 1,
        },
      ],
    },
    1604331182025: {
      kcal: 32,
      name: "Wonton soup",
      portion: 241,
      portions: [
        {
          gramWeight: 241,
          id: 239172,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 1,
        },
      ],
    },
    1604331205755: {
      kcal: 254,
      name: "Hamburger (Burger King)",
      portion: 100,
      portions: [
        {
          gramWeight: 100,
          id: 247759,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60844",
          portionDescription: "1 hamburger",
          sequenceNumber: 1,
        },
      ],
    },
    1604331236385: {
      kcal: 196,
      name: "Potato, french fries, from fresh, fried",
      portion: 60,
      portions: [
        {
          gramWeight: 5,
          id: 260248,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64739",
          portionDescription: "1 fry, NS as to shape",
          sequenceNumber: 1,
        },
        {
          gramWeight: 8,
          id: 260256,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64740",
          portionDescription: "1 spiral or curly",
          sequenceNumber: 4,
        },
        {
          gramWeight: 70,
          id: 259567,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64636",
          portionDescription: "1 medium, raw, yields",
          sequenceNumber: 9,
        },
        {
          gramWeight: 5,
          id: 259559,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64634",
          portionDescription: "1 crinkle cut",
          sequenceNumber: 7,
        },
        {
          gramWeight: 50,
          id: 259565,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64635",
          portionDescription: "1 small, raw, yields",
          sequenceNumber: 8,
        },
        {
          gramWeight: 2,
          id: 259543,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64632",
          portionDescription: "1 shoestring",
          sequenceNumber: 2,
        },
        {
          gramWeight: 100,
          id: 259569,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64637",
          portionDescription: "1 large, raw, yields",
          sequenceNumber: 10,
        },
        {
          gramWeight: 5,
          id: 259551,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64633",
          portionDescription: "1 straight cut",
          sequenceNumber: 3,
        },
        {
          gramWeight: 8,
          id: 259222,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64605",
          portionDescription: "1 waffle",
          sequenceNumber: 5,
        },
        {
          gramWeight: 9,
          id: 253638,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62927",
          portionDescription: "1 wedge",
          sequenceNumber: 6,
        },
        {
          gramWeight: 15,
          id: 243739,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "40061",
          portionDescription: "1 oz, raw, yields",
          sequenceNumber: 12,
        },
        {
          gramWeight: 60,
          id: 239391,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 11,
        },
      ],
    },
    1604342681719: {
      kcal: 52,
      name: "Apple, raw",
      portion: 242,
      portions: [
        {
          gramWeight: 34,
          id: 256154,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "64236",
          portionDescription: "1 single serving package",
          sequenceNumber: 7,
        },
        {
          gramWeight: 165,
          id: 252155,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "62015",
          portionDescription: "1 small",
          sequenceNumber: 1,
        },
        {
          gramWeight: 25,
          id: 251691,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61935",
          portionDescription: "1 slice",
          sequenceNumber: 5,
        },
        {
          gramWeight: 200,
          id: 249331,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "61238",
          portionDescription: "1 medium",
          sequenceNumber: 2,
        },
        {
          gramWeight: 242,
          id: 248284,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60919",
          portionDescription: "1 large",
          sequenceNumber: 3,
        },
        {
          gramWeight: 295,
          id: 247556,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "60749",
          portionDescription: "1 extra large",
          sequenceNumber: 4,
        },
        {
          gramWeight: 125,
          id: 239215,
          measureUnit: {
            abbreviation: "undetermined",
            id: 9999,
            name: "undetermined",
          },
          modifier: "10205",
          portionDescription: "1 cup",
          sequenceNumber: 6,
        },
      ],
    },
  },
];

export const restD = {
  target: 2500,
  targetWeight: 180,
  weight: [173, 175, 178, 187, 185, 175, 170],
};
